<?PHP
// Setup connection to database
$link = mysqli_connect('loadlhost', 'USERNAME', 'PASSWORD') or die("<content><result>mysql connection failed</result></content>");
mysqli_select_db($link, 'DBNAME') or die("<content><result>database selection failed</result></content>");
$name = $_REQUEST['name'];
$brand = $_REQUEST['brand'];
$desc = $_REQUEST['desc'];
$servesize = $_REQUEST['serve_size'];
$cal = $_REQUEST['calories'];
$calfat = $_REQUEST['calories_fat'];
$totfat = $_REQUEST['total_fat'];
$monfat = $_REQUEST['mono_fat'];
$polfat = $_REQUEST['poly_fat'];
$satfat = $_REQUEST['sat_fat'];
$tranfat = $_REQUEST['trans_fat'];
$chol = $_REQUEST['cholesterol'];
$sod = $_REQUEST['sodium'];
$pot = $_REQUEST['potass'];
$totcarb = $_REQUEST['total_carb'];
$dietfiber = $_REQUEST['diet_fiber'];
$sugar = $_REQUEST['sugars'];
$othercarb = $_REQUEST['other_carb'];
$prot = $_REQUEST['protein'];
$vita = $_REQUEST['vit_a'];
$vitc = $_REQUEST['vit_c'];
$calc = $_REQUEST['calc'];
$iron = $_REQUEST['iron'];
$vitd = $_REQUEST['vit_d'];
$vite = $_REQUEST['vit_e'];
$vitk = $_REQUEST['vit_k'];
$thia = $_REQUEST['thia'];
$ribo = $_REQUEST['ribo'];
$nia = $_REQUEST['niacin'];
$vitb6 = $_REQUEST['vit_b6'];
$fol = $_REQUEST['folic'];
$vitb12 = $_REQUEST['vit_b12'];
$bio = $_REQUEST['biotin'];
$panto = $_REQUEST['panto'];
$pho = $_REQUEST['phosph'];
$iodine = $_REQUEST['iodine'];
$mag = $_REQUEST['magnesium'];
$zinc = $_REQUEST['zinc'];
$sel = $_REQUEST['selenium'];
$cop = $_REQUEST['copper'];
$mang = $_REQUEST['mang'];
$chrom = $_REQUEST['chrom'];
$moly = $_REQUEST['moly'];
$query = "INSERT INTO ingredients (";
$query .= "item, item_brand, item_desc, serve_size, calories, calories_fat, total_fat, mono_fat, poly_fat,	sat_fat, ";
$query .= "trans_fat, cholesterol, sodium, potassium, total_carb, diet_fiber, sugars, other_carb, ";
$query .= "protein, vitamin_a, vitamin_c, calcium, iron, vitamin_d, vitamin_e, vitamin_k, thiamin, ";
$query .= "riboflavin, niacin, vitamin_b6, folicacid, vitamin_b12, biotin, pantothenic, phosphorus, ";
$query .= "iodine, magnesium, zinc, selenium, copper, manganese, chromium, molybdenum";
$query .= ")	VALUES (";
$query .= "'$name','$brand','$desc','$servesize','$cal','$calfat','$totfat','$monfat','$polfat',";
$query .= "'$satfat','$tranfat','$chol','$sod','$pot','$totcarb','$dietfiber','$sugar','$othercarb',";
$query .= "'$prot','$vita','$vitc','$calc','$iron','$vitd','$vite','$vitk','$thia','$ribo',";
$query .= "'$nia','$vitb6','$fol','$vitb12','$bio','$panto','$pho','$iodine','$mag','$zinc',";
$query .= "'$sel','$cop','$mang','$chrom','$moly'";
$query .= ");";
//echo "<content><result>" . $query. "</result></content>";
$result = mysqli_query($link, $query) or die("<content><result>failed: " . mysqli_error($link) . "</result></content>");
// Closing connection
mysqli_close($link);
